---

services:
  mongodb:
    image: personalimuno/mongodb:7.0
    restart: always
    ports:
      - 27017/tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["--replSet", "${REPLICASETS}", "--bind_ip_all",  "--keyFile", "/keyfile"]
    volumes:
      - /stacks/mongodb-4.2.12-replset/data:/data/db
      - /stacks/mongodb-4.2.12-replset/config:/data/configdb