---

services:
  mongodb:
    image: luminestudio/dev:mongo-7.0
    restart: always
    ports:
      - ${PORTS}:27017/tcp
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    command: ["--replSet", "${REPLICASETS}", "--bind_ip_all",  "--keyFile", "/keyfile"]
    volumes:
      - /stacks/mongodb-7.0-replset/data:/data/db
      - /stacks/mongodb-7.0-replset/config:/data/configdb